### ISSUE TITLE
Make a list of things in inventory

### ISSUE THREAD

**Issue by Imsiaocong** [nyu-devops-summer-2021-inventory/inventories#1]
**As a** developer
**I need** a database that stores all the information about out inventory
**So that** we can work on the later parts

**Assumptions**
* We will be implementing the database using ! mongoDB on !cloud
* The database is called 'inventory'

**Acceptance Criteria**
```
To be discussed in the meeting
```

**Comment by cslecrone** [comment]
I think we don't have quite enough context for this yet. Maybe we could pivot this to one of the tasks listed in the Homework?

* Create a README.md file and make sure that you give instructions on what calls are available and what inputs they expect and how to run and test your code so that users will know how it works.
* Make sure that you set up a .gitignore file to keep unwanted files out of your
repo. I should not see .vagrant/ folders in your repos.
* Use PyLint to make sure that your code conforms to the PEP8 Python standard. Remember that Python uses camel_case not snakeCase.
* Create a setup.cfg file with all of your nosetests options so that you only have to type nosetests to run the test suite. Place your test cases in a ./tests folder.
* Use Docker inside of your Vagrant VM for any 3rd part services you want to use. e.g., if you use a Redis, MongoDB, PostgreSQL, MySQL database, etc. it should be installed using Docker. If you copied the Vagrantfile from my repo, don’t forget to remove anything from your Vagrantfile that is not needed.
* Start developing by creating the TDD test_xxx.py files that contains your Unit Tests to test your service and model. Use the standard PyUnit syntax that we learned in class.
* Create a models.py file to hold your model definitions of your resource
* Write test cases to test your model
* Create a routes.py file to contain your Flask service routes
* Write test cases to test your service
* There should be tests for each of Create, Read, Update, Delete, List, Query, Action, traversing both happy paths and sad paths
* Use the coverage tool to measure your test coverage. Your goal is get coverage of at least 95%.
* Following good REST API practices, your API should only return json. This includes any error messages from the web server which means you must override the default error handlers and ensure that only json messages are returned.

**Comment by Imsiaocong** [comment]
Sure!
